### ISSUE TITLE
Set Up Airmusic Configuration -> Radio connect to Wifi again

### ISSUE THREAD

**Issue by achmet9948** [DominikWrobel/airmusic#1]
Hi there, I want to add the radio. 
If I add the IP from the radio and press the enter, the radio show's "Conntect to WiFI" 
I already reboot the radio and no App is online.

Can you help me?

**Comment by DominikWrobel** [comment]
Can you tell me the model of your radio and if you can connect it to AirMusic Controll app on Android or iOS? Also in the integration page turn on debugging try to add your radio and after couple of minutes turn it off, you will get a log, which you can paste here.

**Comment by achmet9948** [comment]
My Radio is an imperial 105
I can control the radio via the app.

That is the debug log: 

`custom_components.airmusic] Setting up Airmusic media player from config entry
2024-09-06 15:14:58.130 DEBUG (MainThread) [custom_components.airmusic] Airmusic: [request_call] - Call request http://172.16.5.6/playinfo 
2024-09-06 15:14:59.723 DEBUG (MainThread) [custom_components.airmusic] Airmusic: [request_call] - Call request http://172.16.5.6/playinfo 
2024-09-06 15:15:01.263 ERROR (MainThread) [homeassistant.components.media_player] airmusic: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/airmusic/media_player.py", line 246, in async_update
    await self._update_volume_info()
  File "/config/custom_components/airmusic/media_player.py", line 252, in _update_volume_info
    vol = soup.vol.renderContents().decode('UTF8')
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'renderContents'
2024-09-06 15:15:01.265 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2024-09-06 15:15:01.265 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector (None)`

**Comment by achmet9948** [comment]
I added the device now but I can't control it. See the above log

**Comment by DominikWrobel** [comment]
Ok, so this is your radio IP right?: 172.16.5.6 is it in the same network as Home Assistant? Also when the radio is playing an internet radio station can you type in your browser the radio IP and /playinfo or /init or /background_play_status

Paste any info you get from these pages, you can also try to see if any commands from the remote work: [https://github.com/DominikWrobel/airmusic/tree/main/remote](url)

**Comment by achmet9948** [comment]
The Radio is in a seperate IoT Network - But for troubleshooting the homasssistant can access all Networks. 

I tried http://172.16.5.6/playinfo and got back "401 Unauthorized"
![image](https://github.com/user-attachments/assets/5164cff3-3d16-4a73-b434-bcf6b788f43b)

**Comment by DominikWrobel** [comment]
OK, so your radio has basic auth enabled, but that should not be a problem. If Home Assistant can access the radio IP the integration should work. For troubleshooting try to use this shell_command in configuration.yaml and restart HA:

```
shell_command:
  radio_on_off: "curl -H 'Authorization: Basic c3UzZzRnbzZzazc6amkzOTQ1NHh1L14=' http://172.16.5.6/Sendkey?key=7"
  radio_init: "curl -H 'Authorization: Basic c3UzZzRnbzZzazc6amkzOTQ1NHh1L14=' http://172.16.5.6/init?language=en"
```

radio_on_off command will turn on or off your radio, you can run this from devoloper tools and actions. If there is an error that means Home Assistant can't reach the radio in its IoT network, if it runs then try radio_init command and then try to set up my integration again.

**Comment by achmet9948** [comment]
The Shell Commands are working, but the integration is not working. 

When I try to reconfigure the Entity, the radio is going off and on again and I get this error 
![image](https://github.com/user-attachments/assets/50274435-65a1-45a2-9e1c-2bff7b4518b0)

**Comment by DominikWrobel** [comment]
Hmm...this means your radio has a bit different playinfo setting we can problably fix this just need some more info, first with NodeRED import this:

```
[
    {
        "id": "65ed383bf1bd372f",
        "type": "inject",
        "z": "9a01fb24e639acb0",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 260,
        "y": 700,
        "wires": [
            [
                "976d5872f57da1ea"
            ]
        ]
    },
    {
        "id": "9b75a6328389e1db",
        "type": "debug",
        "z": "9a01fb24e639acb0",
        "name": "debug 12",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 600,
        "y": 700,
        "wires": []
    },
    {
        "id": "976d5872f57da1ea",
        "type": "http request",
        "z": "9a01fb24e639acb0",
        "name": "",
        "method": "GET",
        "ret": "txt",
        "paytoqs": "ignore",
        "url": "http://172.16.5.6/playinfo",
        "tls": "",
        "persist": false,
        "proxy": "",
        "insecureHTTPParser": false,
        "authType": "basic",
        "senderr": false,
        "headers": [],
        "x": 430,
        "y": 700,
        "wires": [
            [
                "9b75a6328389e1db"
            ]
        ]
    }
]
```

In http-request node enter this basic auth details: user: su3g4go6sk7 pass: ji39454xu/^ and deploy and inject, you should get something like this if the radio is playing:

```
"<?xml version="1.0" encoding="UTF-8"?><result><vol>6</vol><mute>0</mute><status>Odtwarzanie </status><sid>6</sid><SF_Exist>0</SF_Exist><station_id>0</station_id><station_name></station_name><logo_img>http://192.168.0.142:8080/playlogo.jpg</logo_img><album_img>http://192.168.0.142:8080/album.jpg</album_img><stream_format>MP3 /128 Kbps</stream_format><station_info></station_info><artist>FRANZ FERDINAND</artist><song>Take Me Out</song><composer></composer><lyricist></lyricist></result>"
```

Maybe the response from your radio is different?

**Comment by achmet9948** [comment]
Got an error:
`<?xml version="1.0" encoding="UTF-8"?><result><rt>INVALID_CMD</rt></result>`

**Comment by DominikWrobel** [comment]
This may be the problem, try to run shell command radio_init and then again the flow I provided. If you still habe INVALID_CMD then open the AirMusic App and connect to the radio, then init the flow. You can also try to see if you can get any info from this adress in NodeRED http://172.16.5.6/background_play_status

**Comment by achmet9948** [comment]
From Radio_Init 

`<?xml version="1.0"
  encoding="UTF-8"?><result><id>1</id><version>jc1420191214h</version><lang>en</lang><wifi_set_url>http://192.168.78.1/scan_wifi</wifi_set_url><ptver>20170921</ptver><hotkey_fav>0</hotkey_fav><push_talk>1</push_talk><leave_msg>1</leave_msg><leave_msg_ios>1</leave_msg_ios><M7_SUPPORT>0</M7_SUPPORT><MKEY_SUPPORT>0</MKEY_SUPPORT><UART_CD>0</UART_CD><PlayMode>1</PlayMode><MaxVol>30</MaxVol><SP_Play>0</SP_Play><cur_play_menu_id>59</cur_play_menu_id><cur_play_name>BOLLERWAGEN</cur_play_name><SWUpdate>NO</SWUpdate></result>`

And after the shell Commadn I run the workflow again: 
Result: 
`<?xml version="1.0" encoding="UTF-8"?><result>FAIL</result>`

**Comment by achmet9948** [comment]
Result with "http://172.16.5.6/background_play_status"

`<?xml version="1.0" encoding="UTF-8"?><result><sid>6</sid><playtime_left>00:00:00</playtime_left><vol>6</vol><mute>0</mute><name></name></result>`

**Comment by DominikWrobel** [comment]
Edit:
FAIL should be shown when radio is off, if radio is playing a station you should get a name. Try again play info when radio is playing

If you have fail even when radio is playing then the init part on your radio forces the radio to do a network scan, playinfo does not give any info only background play status gives some info. This radio may have a limited inteface and will not send info about the current radio station and will not work with this integration, only the commands from the remote will work. You can check if the AirMusic app has info about the station that is playing now;

![airmusicapp](https://github.com/user-attachments/assets/c8549fb6-40ec-4cd2-b542-94d97b43b087)

If you have info about current radio station then we need to find out what backend is the app using to get this info. To do this you will need to install [https://play.google.com/store/apps/details?id=com.emanuelef.remote_capture&hl=pl](url) on your phone, then use the app, choose in traffic dump PCAP file, in target app AirMusic app and start the dump, then play around with the app, change stations, wait for info from the radio etc. When finished in the PCAP app finish the dump and send the resoult to me.

**Comment by achmet9948** [comment]
Ah, I see, that the radio played the music in the backgroud. I opend the view with the radio station and I get now more infos from playinfo: 

`<?xml version="1.0" encoding="UTF-8"?><result><vol>3</vol><mute>0</mute><status>Playing </status><sid>6</sid><SF_Exist>0</SF_Exist><station_id>0</station_id><station_name></station_name><logo_img>http://172.16.5.6:8080/playlogo.jpg</logo_img><stream_format>MP3 /128 Kbps</stream_format><station_info></station_info><artist>NDR 2</artist><song>NDR 2 - ndr.de/ndr2</song><composer></composer><lyricist></lyricist></result>`

**Comment by DominikWrobel** [comment]
Ok now try to start my integration. I think you should delete the first entry and add a new one. If there is info from playinfo backend it should work ok

**Comment by achmet9948** [comment]
So, I remove the Radio in homeassistant und add it again. Now it should work

**Comment by DominikWrobel** [comment]
Yes it should work, I still don't know why when radio scans for network when doing init, it's not supposed to do this. Probably the manufacturer made a mistake in the code

**Comment by achmet9948** [comment]
Okay, after restarting the radio, I have to reinitiate the radio and switch the view to the player. Then I can control the radio again via homeassistant.

**Comment by DominikWrobel** [comment]
Yeah you may have to init the radio after restart, but the integration will keep the connection to the radio open and in normal operation it will just work as is. I think this closes the issue.
